#!/usr/bin/env python3
"""
Derive per-brand detection thresholds from a year of historical transactions.

The dashboard's shipped thresholds are flat: Rule 2 alerts above 20% daily
failure rate, Critical Spike above 40%. Backtested against the full history
those fire on 54.5% of all eligible brand-days, because several brands simply
*operate* above them — SPLUNK's normal rate is 53.5%, VMWARE's 50.4%. An alert
that fires more than half the time carries no information.

This reads the DCA history workbook (one sheet per brand) and emits, per brand,
the distribution of its own daily failure rates. The dashboard uses those
percentiles as thresholds, floored at the documented flat values, so a brand is
judged against its own behaviour and the business rule still holds as a minimum.

It also learns reason-categorisation rules. The history carries a curated
`Reason2` label per row; the live Sheet1 export does not, but the two share
~98% of their PO numbers. Joining on PO recovers a category for free-text
reasons the hand-written keyword map currently misses.

Output is a plain JSON file, regenerated by hand when a new history export
arrives. It is never a runtime dependency: without it the dashboard falls back
to the flat thresholds it shipped with.

    python3 tools/calibrate.py data/history_dca_2026.xlsx data/calibration.json
"""
from __future__ import annotations

import argparse
import collections
import datetime as dt
import json
import re
import statistics
import sys

import openpyxl

# Sheets that hold derived reporting rather than transactions.
NON_BRAND_SHEETS = {"Summary", "Summary2", "Summary3", "Sheet1"}

# A brand-day needs this many transactions before its failure rate means
# anything — the same floor Rule 2 itself uses.
MIN_DAY_VOLUME = 5
# Below this many eligible days a brand's percentiles are too unstable to trust.
# Splitting the history in half and recomputing shows high-volume brands move by
# ~1pp while brands under ~30 days swing by 20-30pp.
MIN_ELIGIBLE_DAYS = 30
# A brand whose *normal* failure rate is this high is chronically
# underperforming. Reported as standing context, never as an alert.
CHRONIC_BASELINE_RATE = 0.40

RULE2_PERCENTILE = 0.90      # threshold for "an unusual day for this brand"
CRITICAL_PERCENTILE = 0.95   # threshold for "a bad day even by this brand's standards"
# Ceiling on any adapted threshold. Without it a brand that degrades badly
# enough raises its own percentiles out of reach and stops alerting entirely:
# TENABLE's p95 is already 100% because of an August regression, which would
# make a critical spike impossible for it. Above this rate, something is wrong
# regardless of what the brand's history says.
MAX_ADAPTIVE_RATE = 0.90

# A learned reason rule needs this much agreement and this many observations
# before it is trusted enough to ship.
LEARN_MIN_CONFIDENCE = 0.80
LEARN_MIN_COUNT = 3


def parse_dt(value):
    """The history stores timestamps as DD/MM/YYYY strings, not datetimes."""
    if isinstance(value, dt.datetime):
        return value
    text = str(value or "").strip()
    m = re.match(r"^(\d{2})/(\d{2})/(\d{4})[ T](\d{1,2}):(\d{2}):(\d{2})", text)
    if m:
        return dt.datetime(int(m[3]), int(m[2]), int(m[1]),
                           int(m[4]), int(m[5]), int(m[6]))
    return None


def percentile(values: list[float], p: float) -> float:
    """Linear interpolation between closest ranks — matches numpy's default and
    the dashboard's own percentile()."""
    if not values:
        return 0.0
    values = sorted(values)
    if len(values) == 1:
        return values[0]
    k = (len(values) - 1) * p
    lo, hi = int(k // 1), min(int(k // 1) + 1, len(values) - 1)
    return values[lo] + (values[hi] - values[lo]) * (k - lo)


def title_case_category(label: str) -> str:
    """Normalise the history's SHOUTED category labels to the sentence case the
    dashboard's own map uses, so the two vocabularies sit together without one
    looking like an error. Also folds the export's case-duplicates
    ('Document missing' / 'Document Missing') onto one key."""
    clean = " ".join(str(label or "").split())
    if not clean:
        return ""
    # Preserve known acronyms that would otherwise be mangled by capitalize().
    words = clean.split(" ")
    out = []
    for i, w in enumerate(words):
        upper = w.upper()
        if upper in {"PO", "SO", "SOD", "MYD", "API", "QTY", "CSI", "DB", "AX"}:
            out.append(upper)
        elif i == 0:
            out.append(w.capitalize())
        else:
            out.append(w.lower())
    return " ".join(out)


def read_history(path: str) -> list[dict]:
    wb = openpyxl.load_workbook(path, read_only=True, data_only=True)
    brands = [s for s in wb.sheetnames if s not in NON_BRAND_SHEETS]
    rows = []
    for sheet in brands:
        ws = wb[sheet]
        it = ws.iter_rows(values_only=True)
        header = [str(c).strip() if c is not None else "" for c in next(it)]
        ix = {h: i for i, h in enumerate(header)}
        need = ("Status", "SentTime")
        if any(k not in ix for k in need):
            print(f"  skipping sheet {sheet!r}: missing {need}", file=sys.stderr)
            continue

        def get(row, key):
            i = ix.get(key)
            return row[i] if i is not None and i < len(row) else None

        for r in it:
            if all(c is None or str(c).strip() == "" for c in r):
                continue
            sent = parse_dt(get(r, "SentTime"))
            if sent is None:
                continue
            status = str(get(r, "Status") or "").strip()
            rows.append({
                "brand": sheet.upper(),
                "order": str(get(r, "OrderNum") or "").strip(),
                "sent": sent,
                # The export spells success "Sucess". Match on the failure side
                # only, so any spelling of the positive case is treated as such.
                "is_failure": status.lower().startswith("fail"),
                "reason2": str(get(r, "Reason2") or "").strip(),
            })
    return rows


def build_brand_profiles(rows: list[dict]) -> dict:
    per_day: dict[tuple, list[int]] = collections.defaultdict(lambda: [0, 0])
    totals: dict[str, list[int]] = collections.defaultdict(lambda: [0, 0])
    for r in rows:
        slot = per_day[(r["brand"], r["sent"].date())]
        slot[0] += 1
        slot[1] += 1 if r["is_failure"] else 0
        t = totals[r["brand"]]
        t[0] += 1
        t[1] += 1 if r["is_failure"] else 0

    by_brand: dict[str, list[tuple]] = collections.defaultdict(list)
    for (brand, day), (n, f) in per_day.items():
        by_brand[brand].append((day, n, f))

    profiles = {}
    for brand, days in sorted(by_brand.items()):
        eligible = [(n, f) for _, n, f in days if n >= MIN_DAY_VOLUME]
        if not eligible:
            continue
        rates = [f / n for n, f in eligible]
        volumes = [n for n, _ in eligible]
        total_n, total_f = totals[brand]
        baseline = total_f / total_n if total_n else 0.0
        reliable = len(eligible) >= MIN_ELIGIBLE_DAYS
        profiles[brand] = {
            "eligibleDays": len(eligible),
            "activeDays": len(days),
            "transactions": total_n,
            "failures": total_f,
            "baselineRate": baseline,
            "p50DailyRate": percentile(rates, 0.50),
            "p90DailyRate": percentile(rates, RULE2_PERCENTILE),
            "p95DailyRate": percentile(rates, CRITICAL_PERCENTILE),
            "medianDailyVolume": statistics.median(volumes),
            "reliable": reliable,
            # Standing context, not an alert: a brand can be "normal" against
            # its own adaptive threshold while still failing half its work.
            "chronic": baseline >= CHRONIC_BASELINE_RATE,
        }
    return profiles


def learn_reason_rules(rows: list[dict], sheet1_payload: str | None) -> list[dict]:
    """Recover categories for free-text reasons the keyword map misses, by
    joining the live export to the history on PO number.

    Only reasons that currently fall through to 'Unspecified' are considered, so
    a learned rule can never override a hand-written one."""
    if not sheet1_payload:
        return []
    try:
        with open(sheet1_payload, encoding="utf-8") as fh:
            payload = json.load(fh)
    except OSError:
        print(f"  no payload at {sheet1_payload}; skipping reason learning", file=sys.stderr)
        return []

    # PO -> most common curated label, failures only.
    by_po: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for r in rows:
        if not r["is_failure"] or not r["order"]:
            continue
        label = r["reason2"]
        if label and label.lower() != "none":
            by_po[r["order"]][title_case_category(label)] += 1

    statuses = payload["statuses"]
    vendors = payload["vendors"]
    reasons = payload["reasons"]

    # Reasons the hand-written map already handles must be left alone.
    sys.path.insert(0, "tools")
    from reference_engine import categorize, DEFAULT_CATEGORY  # noqa: E402

    candidates: dict[str, collections.Counter] = collections.defaultdict(collections.Counter)
    for s, v, rix, po, _date in payload["rows"]:
        if not vendors[v].strip():
            continue
        if statuses[s].strip().casefold() != "failure":
            continue
        text = reasons[rix]
        if categorize(text) != DEFAULT_CATEGORY:
            continue                                  # already mapped
        stripped = str(text).strip()
        if not stripped or stripped.upper() == "N/A":
            continue                                  # genuinely unspecified
        labels = by_po.get(str(po).strip())
        if labels:
            candidates[stripped].update(labels)

    learned = []
    for text, counter in candidates.items():
        label, hits = counter.most_common(1)[0]
        total = sum(counter.values())
        confidence = hits / total if total else 0.0
        if total < LEARN_MIN_COUNT or confidence < LEARN_MIN_CONFIDENCE:
            continue
        learned.append({
            "match": text,
            "category": label,
            "observations": total,
            "confidence": round(confidence, 3),
        })
    # Longest match first: a specific text must win over a shorter one that is a
    # prefix of it, since the dashboard scans rules in order.
    learned.sort(key=lambda r: (-len(r["match"]), -r["observations"]))
    return learned


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("history", nargs="?", default="data/history_dca_2026.xlsx")
    ap.add_argument("out", nargs="?", default="data/calibration.json")
    ap.add_argument("--payload", default="data/sheet1_payload.json",
                    help="live export, used to learn reason rules via the PO join")
    args = ap.parse_args()

    rows = read_history(args.history)
    if not rows:
        raise SystemExit("no transactions read from " + args.history)

    profiles = build_brand_profiles(rows)
    learned = learn_reason_rules(rows, args.payload)
    sent = [r["sent"] for r in rows]

    result = {
        "generated": dt.datetime.now().isoformat(timespec="seconds"),
        "source": args.history,
        "sourceRows": len(rows),
        "sourceFrom": min(sent).isoformat(),
        "sourceTo": max(sent).isoformat(),
        "config": {
            "minDayVolume": MIN_DAY_VOLUME,
            "minEligibleDays": MIN_ELIGIBLE_DAYS,
            "rule2Percentile": RULE2_PERCENTILE,
            "criticalPercentile": CRITICAL_PERCENTILE,
            "chronicBaselineRate": CHRONIC_BASELINE_RATE,
            "maxAdaptiveRate": MAX_ADAPTIVE_RATE,
        },
        "brands": profiles,
        "reasonRules": learned,
    }
    with open(args.out, "w", encoding="utf-8") as fh:
        json.dump(result, fh, indent=1, ensure_ascii=False)

    reliable = sum(1 for p in profiles.values() if p["reliable"])
    chronic = [b for b, p in profiles.items() if p["chronic"]]
    print(f"wrote {args.out}")
    print(f"  history      {len(rows):,} rows, {min(sent):%Y-%m-%d} to {max(sent):%Y-%m-%d}")
    print(f"  brands       {len(profiles)} calibrated, {reliable} reliable "
          f"(>={MIN_ELIGIBLE_DAYS} eligible days)")
    print(f"  chronic      {len(chronic)}: {', '.join(sorted(chronic))}")
    print(f"  reason rules {len(learned)} learned "
          f"(>={LEARN_MIN_COUNT} obs, >={LEARN_MIN_CONFIDENCE:.0%} confidence)")
    print()
    print(f"  {'brand':13s} {'days':>5s} {'base':>7s} {'p90':>7s} {'p95':>7s}  reliable chronic")
    for brand, p in sorted(profiles.items()):
        print(f"  {brand:13s} {p['eligibleDays']:5d} {p['baselineRate']:7.1%} "
              f"{p['p90DailyRate']:7.1%} {p['p95DailyRate']:7.1%}  "
              f"{'yes' if p['reliable'] else 'NO ':>8s} {'yes' if p['chronic'] else '-':>7s}")


if __name__ == "__main__":
    main()
